package redbacks.robot.subsystems.aiming;

public class AimingConstants {
    static final double
        HUB_HEIGHT_METRES = 2.595,
        HUB_RADIUS_METRES = 0.68,
        LIMELIGHT_HEIGHT_METRES = 0.835,
        TURRET_OFFSET_FROM_LIMELIGHT_METRES = 0.245,
        ROBOT_CENTRE_OFFSET_FROM_TURRET_METRES = 0.132,
        LIMELIGHT_ANGLE_RADIANS = Math.toRadians(36),
        LIMELIGHT_TO_HUB_HEIGHT_METRES = HUB_HEIGHT_METRES - LIMELIGHT_HEIGHT_METRES,
        AIMING_TOLERANCE_MULTIPLIER = 0.5,
        HOOD_ANGLE_TOLERANCE_DEGREES = 0.8,
        LIMELIGHT_YAW_OFFSET_DEGREES = 3,
        DISCARD_TURRET_TOLERANCE_DEGREES = 5,
        TURRET_STOW_POSITION_DEGREES = -90,

        MIN_SHOOT_WHILE_MOVING_DISTANCE_METRES = 10,
        MAX_SHOOT_WHILE_MOVING_DISTANCE_METRES = 10,

        CLOSE_MAX_ROBOT_SPEED_STATIONARY_SHOOTING = 0.3,
        FAR_MAX_ROBOT_SPEED_STATIONARY_SHOOTING = 0.1;

    static final int
        VELOCITY_X_MAP_INCREMENT_MM = 50,
        VELOCITY_Y_MAP_INCREMENT_MM = 50;
}
