package redbacks.robot.subsystems.shooter;

import redbacks.robot.Constants;

public class ShooterConstants {
    private static final double
        GEAR_RATIO_MOTOR_TO_FLYWHEEL = 24d / 48d,
        GEAR_RATIO_FLYWHEEL_TO_REARWHEEL = 48d / 60d,
        FLYWHEEL_TICKS_PER_REVOLUTION = Constants.TALON_FX_TICKS_PER_REVOLUTION / GEAR_RATIO_MOTOR_TO_FLYWHEEL,
        REARWHEEL_TICKS_PER_REVOLUTION = FLYWHEEL_TICKS_PER_REVOLUTION / GEAR_RATIO_FLYWHEEL_TO_REARWHEEL,
        FLYWHEEL_CIRCUMFERENCE_METRES = Math.PI * 0.105,
        REARWHEEL_CIRCUMFERENCE_METRES = Math.PI * 0.046,
        FLYWHEEL_TICKS_PER_METRE = FLYWHEEL_TICKS_PER_REVOLUTION / FLYWHEEL_CIRCUMFERENCE_METRES,
        REARWHEEL_TICKS_PER_METRE = REARWHEEL_TICKS_PER_REVOLUTION / REARWHEEL_CIRCUMFERENCE_METRES,
        BALL_TICKS_PER_METRE = (FLYWHEEL_TICKS_PER_METRE + REARWHEEL_TICKS_PER_METRE) / 2;

    static final double TICKS_PER_100MS_TO_METRES_PER_SECOND = 10 / BALL_TICKS_PER_METRE;

    static final double
        SHOOTING_TARGET_MPS = 7.7,
        LOW_GOAL_SHOOTING_TARGET_MPS = 5.8,
        IDLE_TARGET_MPS = 5,
        TARGET_MPS_TOLERANCE = 0.15,
        SPEED_OFFSET_INCREMENT_MPS = 0.1,
        STARTING_SHOOTER_SPEED_OFFSET = -0.3;

    static final double
        KP = 0.15,
        KI = 0,
        KD = 1,
        MAX_PID_OUTPUT = 1,
        RAMP_TIME_SECONDS = 1;
}